repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.1
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_validate
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.22
  hooks:
      - id: terragrunt-hclfmt