name: Trigger aws Live REPO

on: 
  push:
    branches:
      - dev
      - release
    paths:
      - 'aws/**'
jobs:
  trigger_workflow:
    runs-on: medium
    steps:
      - name: Trigger infra-aws-live dev env
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
            owner: 'shan',
            repo: 'infra-live-aws-temp',
            workflow_id: 'cicd.yaml',
            ref: 'dev'
            })
      - name: Trigger infra-aws-live pre env
        if: github.ref == 'refs/heads/release' && github.event_name == 'push'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
            owner: 'shan',
            repo: 'infra-live-aws-temp',
            workflow_id: 'cicd.yaml',
            ref: 'release'
            })
